import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import process from 'node:process';

import {
  HOSTS_BEGIN_MARKER,
  HOSTS_END_MARKER,
  MACOS_PF_ANCHOR_NAME,
  MACOS_PF_ANCHOR_PATH,
  buildManagedHostsEntries,
  dataset,
} from '../domain/policy.mjs';
import {
  detectLineEnding,
  fileExists,
  readFileTextSafe,
} from './fs-utils.mjs';
import { commandExists, runCommand } from './process-utils.mjs';

export function defaultHostsPath() {
  if (process.platform === 'win32') {
    const systemRoot = process.env.SystemRoot || 'C:\\Windows';
    return path.join(systemRoot, 'System32', 'drivers', 'etc', 'hosts');
  }
  return '/etc/hosts';
}

export function buildHostsBlockContent(lineEnding = os.EOL) {
  const lines = [
    HOSTS_BEGIN_MARKER,
    '# Generated by src/cli/scan-supply-chain-campaigns.mjs',
    '# These entries cover attacker-controlled or campaign-specific domains documented',
    '# across the Axios incident and the Shai-Hulud / Mini-Shai-Hulud family.',
  ];

  for (const entry of buildManagedHostsEntries()) {
    lines.push(entry.line);
  }

  lines.push(HOSTS_END_MARKER);
  return lines.join(lineEnding) + lineEnding;
}

export function buildFirewallBlockContent() {
  const lines = [
    '# Firewall/IP blocklist for supply-chain 2026 campaigns',
    '# Note: hosts files cannot block raw IPs.',
  ];

  for (const ip of dataset.networkIndicators.firewallIpBlocklist) {
    lines.push(ip);
  }

  return lines.join(os.EOL) + os.EOL;
}

export function writeBlocklists(dirPath) {
  fs.mkdirSync(dirPath, { recursive: true });
  const hostsPath = path.join(dirPath, 'supply-chain-2026.hosts');
  const firewallPath = path.join(dirPath, 'supply-chain-2026-firewall.txt');

  fs.writeFileSync(hostsPath, buildHostsBlockContent(), 'utf8');
  fs.writeFileSync(firewallPath, buildFirewallBlockContent(), 'utf8');

  return { hostsPath, firewallPath };
}

export function auditHostsFile(hostsPath) {
  const requiredEntries = buildManagedHostsEntries();
  try {
    const text = fileExists(hostsPath) ? readFileTextSafe(hostsPath) : '';
    const existingEntries = parseHostsEntries(text);
    const presentEntries = [];
    const missingEntries = [];

    for (const entry of requiredEntries) {
      const present = hostAuditKeys(entry).some((key) => existingEntries.has(key));
      if (present) {
        presentEntries.push(entry);
      } else {
        missingEntries.push(entry);
      }
    }

    return {
      path: hostsPath,
      readable: true,
      requiredEntries,
      presentEntries,
      missingEntries,
      error: null,
    };
  } catch (error) {
    return {
      path: hostsPath,
      readable: false,
      requiredEntries,
      presentEntries: [],
      missingEntries: requiredEntries,
      error: error.message,
    };
  }
}

export function applyHostsFile(hostsPath) {
  const existingText = fileExists(hostsPath) ? readFileTextSafe(hostsPath) : '';
  const lineEnding = detectLineEnding(existingText);
  const managedSection = buildHostsBlockContent(lineEnding);
  const nextText = replaceManagedSection(
    existingText,
    HOSTS_BEGIN_MARKER,
    HOSTS_END_MARKER,
    managedSection,
    lineEnding,
  );
  fs.writeFileSync(hostsPath, nextText, 'utf8');
}

export function auditTrashState() {
  if (process.platform === 'win32') {
    return auditWindowsTrashState();
  }
  if (process.platform === 'darwin') {
    return auditMacosTrashState();
  }
  if (process.platform === 'linux') {
    return auditLinuxTrashState();
  }
  return {
    provider: 'unsupported',
    supported: false,
    available: false,
    hasItems: null,
    itemCount: null,
    command: null,
    path: null,
    warnings: [],
    error: `No native trash/remediation adapter is implemented for platform ${process.platform}.`,
  };
}

export function emptyTrash() {
  if (process.platform === 'win32') {
    return emptyWindowsTrash();
  }
  if (process.platform === 'darwin') {
    return emptyMacosTrash();
  }
  if (process.platform === 'linux') {
    return emptyLinuxTrash();
  }
  return {
    provider: 'unsupported',
    supported: false,
    available: false,
    attempted: false,
    succeeded: false,
    command: null,
    warnings: [],
    error: `No native trash/remediation adapter is implemented for platform ${process.platform}.`,
  };
}

export function applyFirewallRules() {
  if (process.platform === 'win32') {
    return applyWindowsFirewallRules();
  }
  if (process.platform === 'linux') {
    return applyLinuxFirewallRules();
  }
  if (process.platform === 'darwin') {
    return applyMacosFirewallRules();
  }
  return {
    provider: 'unsupported',
    available: false,
    active: null,
    requiresElevation: false,
    warnings: [],
    ruleResults: [],
    error: `No firewall remediation adapter is implemented for platform ${process.platform}.`,
  };
}

function parseHostsEntries(text) {
  const entries = new Set();
  for (const rawLine of text.split(/\r?\n/u)) {
    const line = rawLine.replace(/\s*#.*/, '').trim();
    if (!line) {
      continue;
    }
    const tokens = line.split(/\s+/u);
    if (tokens.length < 2) {
      continue;
    }
    const [address, ...hosts] = tokens;
    const normalizedAddress = address.toLowerCase();
    for (const host of hosts) {
      entries.add(`${normalizedAddress} ${host.toLowerCase()}`);
    }
  }
  return entries;
}

function hostAuditKeys(entry) {
  if (entry.address === '0.0.0.0') {
    return [
      `0.0.0.0 ${entry.domain.toLowerCase()}`,
      `127.0.0.1 ${entry.domain.toLowerCase()}`,
    ];
  }
  return [`${entry.address.toLowerCase()} ${entry.domain.toLowerCase()}`];
}

function replaceManagedSection(existingText, beginMarker, endMarker, managedSection, lineEnding) {
  const existing = existingText ?? '';
  const beginIndex = existing.indexOf(beginMarker);
  const endIndex = existing.indexOf(endMarker);

  if (beginIndex >= 0 && endIndex >= beginIndex) {
    const before = existing.slice(0, beginIndex).trimEnd();
    const after = existing.slice(endIndex + endMarker.length).trimStart();
    const pieces = [];
    if (before) {
      pieces.push(before);
    }
    pieces.push(managedSection.trimEnd());
    if (after) {
      pieces.push(after);
    }
    return pieces.join(lineEnding + lineEnding) + lineEnding;
  }

  const separator = existing.trim().length > 0 ? lineEnding + lineEnding : '';
  return `${existing.trimEnd()}${separator}${managedSection}`.replace(/^\s+/, '');
}

function buildTrashAudit(provider) {
  return {
    provider,
    supported: true,
    available: true,
    hasItems: null,
    itemCount: null,
    command: null,
    path: null,
    warnings: [],
    error: null,
  };
}

function buildTrashAction(provider) {
  return {
    provider,
    supported: true,
    available: true,
    attempted: false,
    succeeded: false,
    command: null,
    warnings: [],
    error: null,
  };
}

function countImmediateEntries(directoryPath) {
  if (!fileExists(directoryPath)) {
    return 0;
  }
  try {
    return fs.readdirSync(directoryPath, { withFileTypes: true }).length;
  } catch {
    return 0;
  }
}

function runPowerShellCommand(command) {
  return runCommand('powershell', [
    '-NoProfile',
    '-NonInteractive',
    '-ExecutionPolicy',
    'Bypass',
    '-Command',
    command,
  ]);
}

function escapePowerShellSingleQuotedString(value) {
  return value.replace(/'/g, "''");
}

function isPowerShellAvailable() {
  return commandExists('powershell', [
    '-NoProfile',
    '-NonInteractive',
    '-Command',
    'Write-Output ok',
  ]);
}

function auditWindowsTrashState() {
  const audit = buildTrashAudit('powershell-clearrecyclebin');
  audit.command = 'Clear-RecycleBin -Force';
  if (!isPowerShellAvailable()) {
    audit.supported = false;
    audit.available = false;
    audit.error = 'PowerShell is not available on this system.';
    return audit;
  }

  const commandCheck = runPowerShellCommand(
    "if (Get-Command Clear-RecycleBin -ErrorAction SilentlyContinue) { 'present' } else { 'missing' }",
  );
  if (commandCheck.error || commandCheck.status !== 0 || !/\bpresent\b/i.test(commandCheck.stdout ?? '')) {
    audit.supported = false;
    audit.available = false;
    audit.error =
      commandCheck.error?.message ||
      commandCheck.stderr?.trim() ||
      'Clear-RecycleBin is not available in PowerShell on this system.';
    return audit;
  }

  const countResult = runPowerShellCommand(
    "$shell = New-Object -ComObject Shell.Application; $trash = $shell.Namespace(0xA); if ($null -eq $trash) { '0' } else { [string](@($trash.Items()).Count) }",
  );
  if (countResult.error || countResult.status !== 0) {
    audit.error = countResult.error?.message || countResult.stderr?.trim() || 'Could not inspect the Windows recycle bin.';
    return audit;
  }

  const itemCount = Number.parseInt((countResult.stdout ?? '').trim(), 10);
  audit.itemCount = Number.isInteger(itemCount) ? itemCount : null;
  audit.hasItems = Number.isInteger(itemCount) ? itemCount > 0 : null;
  return audit;
}

function emptyWindowsTrash() {
  const action = buildTrashAction('powershell-clearrecyclebin');
  action.command = 'Clear-RecycleBin -Force';
  if (!isPowerShellAvailable()) {
    action.supported = false;
    action.available = false;
    action.error = 'PowerShell is not available on this system.';
    return action;
  }

  action.attempted = true;
  const result = runPowerShellCommand(
    "$ErrorActionPreference = 'Stop'; Clear-RecycleBin -Force -Confirm:$false; 'cleared'",
  );
  if (result.error || result.status !== 0) {
    action.error = result.error?.message || result.stderr?.trim() || 'Could not clear the Windows recycle bin.';
    return action;
  }

  action.succeeded = true;
  return action;
}

function auditMacosTrashState() {
  const audit = buildTrashAudit('osascript-finder-trash');
  audit.command = 'osascript -e \'tell application "Finder" to empty the trash\'';
  audit.path = path.join(os.homedir(), '.Trash');
  if (!commandExists('osascript', ['-e', 'return 1'])) {
    audit.supported = false;
    audit.available = false;
    audit.error = 'osascript is not available on this system.';
    return audit;
  }
  audit.itemCount = countImmediateEntries(audit.path);
  audit.hasItems = audit.itemCount > 0;
  return audit;
}

function emptyMacosTrash() {
  const action = buildTrashAction('osascript-finder-trash');
  action.command = 'osascript -e \'tell application "Finder" to empty the trash\'';
  if (!commandExists('osascript', ['-e', 'return 1'])) {
    action.supported = false;
    action.available = false;
    action.error = 'osascript is not available on this system.';
    return action;
  }

  action.attempted = true;
  const result = runCommand('osascript', [
    '-e',
    'try',
    '-e',
    'tell application "Finder" to empty the trash',
    '-e',
    'end try',
  ]);
  if (result.error || result.status !== 0) {
    action.error = result.error?.message || result.stderr?.trim() || 'Could not empty the macOS trash.';
    return action;
  }

  action.succeeded = true;
  return action;
}

function linuxTrashFilesPath() {
  const dataHome = process.env.XDG_DATA_HOME || path.join(os.homedir(), '.local', 'share');
  return path.join(dataHome, 'Trash', 'files');
}

function parseNonEmptyLineCount(text) {
  return (text ?? '')
    .split(/\r?\n/u)
    .map((line) => line.trim())
    .filter(Boolean)
    .length;
}

function auditLinuxTrashState() {
  const trashFilesPath = linuxTrashFilesPath();
  const gioList = runCommand('gio', ['trash', '--list']);
  if (!(gioList.error && gioList.error.code === 'ENOENT') && (gioList.status ?? 0) === 0) {
    const audit = buildTrashAudit('gio-trash');
    audit.command = 'gio trash --empty';
    audit.path = trashFilesPath;
    audit.itemCount = parseNonEmptyLineCount(gioList.stdout);
    audit.hasItems = audit.itemCount > 0;
    return audit;
  }

  if (commandExists('gvfs-trash', ['--help'])) {
    const audit = buildTrashAudit('gvfs-trash');
    audit.command = 'gvfs-trash --empty';
    audit.path = trashFilesPath;
    audit.itemCount = countImmediateEntries(trashFilesPath);
    audit.hasItems = audit.itemCount > 0;
    audit.warnings.push('Using deprecated gvfs-trash fallback because gio trash is unavailable.');
    return audit;
  }

  const audit = buildTrashAudit('unsupported');
  audit.supported = false;
  audit.available = false;
  audit.path = trashFilesPath;
  audit.itemCount = countImmediateEntries(trashFilesPath);
  audit.hasItems = audit.itemCount > 0;
  audit.command = null;
  audit.error = 'No supported Ubuntu/Linux trash-empty command is available (gio trash --empty or gvfs-trash --empty).';
  return audit;
}

function emptyLinuxTrash() {
  const audit = auditLinuxTrashState();
  if (audit.provider === 'gio-trash') {
    const action = buildTrashAction('gio-trash');
    action.command = 'gio trash --empty';
    action.attempted = true;
    const gioEmpty = runCommand('gio', ['trash', '--empty']);
    if (gioEmpty.status === 0) {
      action.succeeded = true;
      return action;
    }
    action.error = gioEmpty.error?.message || gioEmpty.stderr?.trim() || 'Could not empty the trash with gio.';
    return action;
  }

  if (audit.provider === 'gvfs-trash') {
    const action = buildTrashAction('gvfs-trash');
    action.command = 'gvfs-trash --empty';
    action.warnings.push('Using deprecated gvfs-trash fallback because gio trash is unavailable.');
    action.attempted = true;
    const result = runCommand('gvfs-trash', ['--empty']);
    if (result.error || result.status !== 0) {
      action.error = result.error?.message || result.stderr?.trim() || 'Could not empty the trash with gvfs-trash.';
      return action;
    }
    action.succeeded = true;
    return action;
  }

  const action = buildTrashAction('unsupported');
  action.supported = false;
  action.available = false;
  action.error = 'No supported Ubuntu/Linux trash-empty command is available (gio trash --empty or gvfs-trash --empty).';
  return action;
}

function buildWindowsFirewallRuleName(ip) {
  return `CyberT33N supply-chain 2026 block ${ip}`;
}

function buildFirewallAudit(provider) {
  return {
    provider,
    available: true,
    active: null,
    requiresElevation: false,
    warnings: [],
    ruleResults: [],
    error: null,
  };
}

function applyWindowsFirewallRules() {
  const audit = buildFirewallAudit('powershell-netsecurity');
  const adminCheck = runPowerShellCommand(
    "$principal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent()); if ($principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) { 'true' } else { 'false' }",
  );
  if (adminCheck.error || adminCheck.status !== 0) {
    audit.error = adminCheck.error?.message || adminCheck.stderr?.trim() || 'PowerShell admin check failed.';
    return audit;
  }
  if (!/\btrue\b/i.test(adminCheck.stdout ?? '')) {
    audit.requiresElevation = true;
    audit.error = 'Administrator rights are required to create Windows firewall rules.';
    return audit;
  }

  audit.active = true;
  for (const ip of dataset.networkIndicators.firewallIpBlocklist) {
    const ruleName = buildWindowsFirewallRuleName(ip);
    const escapedRuleName = escapePowerShellSingleQuotedString(ruleName);
    const escapedIp = escapePowerShellSingleQuotedString(ip);
    const check = runPowerShellCommand(
      `if (Get-NetFirewallRule -DisplayName '${escapedRuleName}' -ErrorAction SilentlyContinue) { 'present' }`,
    );
    if ((check.stdout ?? '').includes('present')) {
      audit.ruleResults.push({
        target: ip,
        status: 'present',
        detail: ruleName,
      });
      continue;
    }

    const apply = runPowerShellCommand(
      `New-NetFirewallRule -DisplayName '${escapedRuleName}' -Direction Outbound -Action Block -RemoteAddress '${escapedIp}' | Out-Null; 'applied'`,
    );
    if (apply.status === 0 && (apply.stdout ?? '').includes('applied')) {
      audit.ruleResults.push({
        target: ip,
        status: 'applied',
        detail: ruleName,
      });
      continue;
    }

    audit.ruleResults.push({
      target: ip,
      status: 'failed',
      detail: apply.stderr?.trim() || apply.error?.message || `Could not apply Windows firewall rule for ${ip}.`,
    });
  }

  return audit;
}

function applyLinuxFirewallRules() {
  const audit = buildFirewallAudit('ufw');
  const status = runCommand('ufw', ['status', 'numbered']);
  if (status.error && status.error.code === 'ENOENT') {
    audit.available = false;
    audit.error = 'ufw is not installed on this system.';
    return audit;
  }

  const statusText = `${status.stdout ?? ''}${status.stderr ?? ''}`;
  audit.active = /Status:\s+active/i.test(statusText);

  for (const ip of dataset.networkIndicators.firewallIpBlocklist) {
    const present =
      new RegExp(`\\b${ip.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'u').test(statusText) &&
      /DENY OUT/i.test(statusText);
    audit.ruleResults.push({
      target: ip,
      status: present ? 'present' : 'missing',
      detail: `ufw deny out to ${ip}`,
    });
  }

  if (typeof process.getuid === 'function' && process.getuid() !== 0) {
    audit.requiresElevation = true;
    audit.error = 'Root privileges are required to modify ufw rules.';
    if (!audit.active) {
      audit.warnings.push('ufw is installed but currently inactive.');
    }
    return audit;
  }

  for (const ruleResult of audit.ruleResults) {
    if (ruleResult.status === 'present') {
      continue;
    }
    const apply = runCommand('ufw', ['deny', 'out', 'to', ruleResult.target]);
    if (apply.status === 0) {
      ruleResult.status = 'applied';
      continue;
    }
    ruleResult.status = 'failed';
    ruleResult.detail = apply.stderr?.trim() || apply.stdout?.trim() || `Could not apply ufw rule for ${ruleResult.target}.`;
  }

  if (!audit.active) {
    audit.warnings.push('ufw rules were updated, but ufw is currently inactive.');
  }
  return audit;
}

function buildMacosPfAnchorContent(lineEnding = os.EOL) {
  const lines = [
    '# Generated by src/cli/scan-supply-chain-campaigns.mjs',
    '# Managed live pf anchor for supply-chain 2026 IOC IP blocking.',
  ];
  for (const ip of dataset.networkIndicators.firewallIpBlocklist) {
    lines.push(`block drop out quick to ${ip}`);
  }
  return lines.join(lineEnding) + lineEnding;
}

function applyMacosFirewallRules() {
  const audit = buildFirewallAudit('pfctl');
  if (!commandExists('/sbin/pfctl', ['-s', 'info'])) {
    audit.available = false;
    audit.error = 'pfctl is not available on this system.';
    return audit;
  }

  const info = runCommand('/sbin/pfctl', ['-s', 'info']);
  audit.active = /Status:\s+Enabled/i.test(info.stdout ?? '');

  let existingAnchorText = '';
  if (fileExists(MACOS_PF_ANCHOR_PATH)) {
    try {
      existingAnchorText = readFileTextSafe(MACOS_PF_ANCHOR_PATH);
    } catch {
      existingAnchorText = '';
    }
  }

  for (const ip of dataset.networkIndicators.firewallIpBlocklist) {
    const present = existingAnchorText.includes(ip);
    audit.ruleResults.push({
      target: ip,
      status: present ? 'present' : 'missing',
      detail: `${MACOS_PF_ANCHOR_PATH} -> block drop out quick to ${ip}`,
    });
  }

  if (typeof process.getuid === 'function' && process.getuid() !== 0) {
    audit.requiresElevation = true;
    audit.error = 'Root privileges are required to modify pf rules on macOS.';
    if (!audit.active) {
      audit.warnings.push('pf is currently disabled.');
    }
    return audit;
  }

  try {
    fs.writeFileSync(
      MACOS_PF_ANCHOR_PATH,
      buildMacosPfAnchorContent(detectLineEnding(existingAnchorText)),
      'utf8',
    );
  } catch (error) {
    audit.error = `Could not write pf anchor file: ${error.message}`;
    return audit;
  }

  const load = runCommand('/sbin/pfctl', ['-a', MACOS_PF_ANCHOR_NAME, '-f', MACOS_PF_ANCHOR_PATH]);
  if (load.status !== 0) {
    audit.error = load.stderr?.trim() || `Could not load pf anchor ${MACOS_PF_ANCHOR_NAME}.`;
    return audit;
  }

  if (!audit.active) {
    const enable = runCommand('/sbin/pfctl', ['-E']);
    if (enable.status === 0) {
      audit.active = true;
    } else {
      audit.warnings.push('pf anchor was loaded, but pf could not be enabled automatically.');
    }
  }

  for (const ruleResult of audit.ruleResults) {
    if (ruleResult.status === 'missing') {
      ruleResult.status = 'applied';
    }
  }
  return audit;
}
