minimumReleaseAge: 10080
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeStrict: true
minimumReleaseAgeExclude: []
trustPolicy: no-downgrade
trustPolicyExclude: []
blockExoticSubdeps: true
strictDepBuilds: true
allowBuilds:
  esbuild: true
dangerouslyAllowAllBuilds: false

registries:
  default: https://registry.npmjs.org/
strictSsl: true

nodeVersion: 24.16.0
engineStrict: true
pmOnFail: error
runtimeOnFail: error

lockfile: true
preferFrozenLockfile: true
lockfileIncludeTarballUrl: true
resolutionMode: time-based
registrySupportsTimeField: false

nodeLinker: isolated
enableGlobalVirtualStore: false
hoist: false
hoistPattern: []
publicHoistPattern: []
shamefullyHoist: false
virtualStoreDir: .pnpm
virtualStoreDirMaxLength: 60
verifyStoreIntegrity: true
strictStorePkgContentCheck: true

autoInstallPeers: false
strictPeerDependencies: true
peerDependencyRules:
  ignoreMissing: []
  allowAny: []
ignoreCompatibilityDb: true
updateNotifier: false
saveExact: true

catalog:
  '@types/node': 25.8.0
  minimatch: 10.2.5
  semver: 7.8.0
  tsx: 4.22.1
  typescript: 6.0.3
  yaml: 2.9.0
catalogMode: strict
cleanupUnusedCatalogs: true

enablePrePostScripts: false
verifyDepsBeforeRun: error
